### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [MIV-XJTU/ARTrack#12]
Hello, 

I really liked your work it is a great work! I am wondering if you will share the trained models? I could not find them in the repo is it missed or something ?

**Comment by AlexDotHam** [comment]
Since I merged two codes into one, the checkpoints I previously trained may no longer apply (for example, the accuracy of my ViT-L was actually trained with a prompt length of 3. Due to the time pressure for the paper submission, the subsequent ablation studies showing that increasing prompt length can effectively improve accuracy were conducted on ViT-B 256), so I may not be able to provide checkpoints that match this code. I will release the checkpoint and corresponding training log for ARTrack-base_256 in the near future, please bear with me for a while (mainly because I really don't have many GPUs I can use recently). However, since I cannot use A6000, I may not be able to provide the checkpoint for ARTrack-Large. If you need to train it, you can email me and I can send you the corresponding yaml file.

**Comment by MUHAMMEDZEYN** [comment]
First thanks for your fast reply, I am actually now out of GPUs too but I wanted to test inference and visualize the outputs. Since you will release them later I can wait for them, great job again ! 

Have a nice day
