### ISSUE TITLE
Identity embeddings

### ISSUE THREAD

**Issue by Leonhard-Euler-ai** [MIV-XJTU/ARTrack#21]
How much impact does adding identity embeddings of template and  search on model performance？

**Comment by AlexDotHam** [comment]
In our experimental setup, we found that whether or not identity embeddings were added had little impact on the final results, with a difference of around 0.2%.

**Comment by Leonhard-Euler-ai** [comment]
Thank you! Another issue is that the paper does not describe additional encoder besides OSTrack, but there are 3x fusion layers in the pix head in the code. I would like to know the reason and the performance difference.

**Comment by AlexDotHam** [comment]
The extra three encoder layers are for providing directional feature matching. You can introduce this directionality in the encoder stage itself using masking, which will give better accuracy (and eliminate the 3x encoders).

**Comment by AlexDotHam** [comment]
Firstly, the accuracy improvement does not come from the 3x encoder, but because my experiments were not sufficiently thorough when I was writing the paper. The 3x encoder can greatly improve the training stability. If you remove this structure, you may also achieve the same accuracy with more epochs.

You understand point 2 correctly. We need to provide the start and end tokens, thus requiring adding 2. However, removing this part during training does not have an obvious impact on accuracy. It is merely to align with the relevant settings of Pix2Seq. I hope this explanation helps with your understanding.

**Comment by Leonhard-Euler-ai** [comment]
I understand. Thank you for your patient reply.
