### ISSUE TITLE
the second stage of training issue

### ISSUE THREAD

**Issue by June-hui** [MIV-XJTU/ARTrack#22]
Why is the second stage of training so slow, and how can I speed it up?

**Comment by AlexDotHam** [comment]
The training in the second stage is frame-by-frame training, that is, sampling a sequence and eliminating the mismatch between training and inference through frame-by-frame inference. Therefore, parallel training is not achieved, which leads to slow training.

We did not propose a good training strategy to correct this scheme. We believe it is precisely because of such a training paradigm that accuracy has improved.

**Comment by June-hui** [comment]
ok,thank you,have a good day~
