### ISSUE TITLE
About ARTrackV2 

### ISSUE THREAD

**Issue by rainbowsea123** [MIV-XJTU/ARTrack#43]
Hello, thank you so much for your great works! And I am wondering if there are any plans to release the code for V2 in the upcoming weeks?

**Comment by AlexDotHam** [comment]
We need to consult with the patent department on this point, and I hope that I can open source my code as much as possible within my ability. If open source is not possible, I think you can easily reproduce our code because our structure is so simple that we only need a backbone and a mask decoder extracted from the MAE code.

Based on this codebase, you can make this in one day. 

If u have any problem u can email me, or add my wechat if u want to, i will try my best to provide the file u need.

**Comment by rainbowsea123** [comment]
OK, thanks a lot for letting me know!
