### ISSUE TITLE
when is upload date your ARTrackv2?

### ISSUE THREAD

**Issue by LiamSumin** [MIV-XJTU/ARTrack#51]
When is the upload date for ARTrackv2?

I wand to know your source code for implementing about your paper!

**Comment by AlexDotHam** [comment]
We need to consult with the patent department on this point, and I hope that I can open source my code as much as possible within my ability. If open source is not possible, I think you can easily reproduce our code because our structure is so simple that we only need a backbone and a mask decoder extracted from the MAE code.

Based on this codebase, you can make this in one day.

If u have any problem u can email me, or add my wechat if u want to, i will try my best to provide the file u need.

**Comment by AlexDotHam** [comment]
We release a temporal code for inference, if you need the training code, we will released that when we finish the ARTrackV3. (the code is not organized and we will merge that into ARTrackV1 when I have enough time.)
