### ISSUE TITLE
About image crops from bbox

### ISSUE THREAD

**Issue by 20throokie** [MIV-XJTU/ARTrack#79]
I found the implementation in code `crop_sz = math.ceil(math.sqrt(w * h) * search_area_factor)` cannot cover objects that have a far distinct height and width. I wonder whether this may hurt performance or not.

**Comment by AlexDotHam** [comment]
In the most extreme cases, when search_area_factor=4, the maximum width or height can be up to 
4
2
4 
2
  times the minimum width or height. In datasets such as GOT-10k, TrackingNet, or LaSOT, I believe this does not have any significant impact because there are no objects with aspect ratios where the width and height differ by more than 16 times.

Additionally, you provide an interesting perspective on crop-based SOT methods. We have followed the dataset implementation as in OSTrack, which uses this kind of crop code. However, if we continue to use the crop-based method, this issue cannot be perfectly resolved. Crop-based methods are a compromise between precision and FPS, and extreme situations may remain problematic.

**Comment by AlexDotHam** [comment]
In the most extreme cases, when search_area_factor=4, the maximum width or height can be up to 4**2 times the minimum width or height. In datasets such as GOT-10k, TrackingNet, or LaSOT, I believe this does not have any significant impact because there are no objects with aspect ratios where the width and height differ by more than 16 times.

Moreover, when we crop the template, the limitation is smaller than the search, because the factor is equal to 2, so the target is no longer beyond 4 times between max of w or h to min of w or h. If we conduct the crop, we can see this situation as a kind of augmentation of data, even if we lose kind of appearance, the tracker is asked to give the whole object location.

Additionally, you provide an interesting perspective on crop-based SOT methods. We have followed the dataset implementation as in OSTrack, which uses this kind of crop code. However, if we continue to use the crop-based method, this issue cannot be perfectly resolved. Crop-based methods are a compromise between precision and FPS, and extreme situations may remain problematic.
