### ISSUE TITLE
Params and FLOPs

### ISSUE THREAD

**Issue by jiabingxiing** [MIV-XJTU/ARTrack#80]
Thanks for the author's excellent work. 
I'm curious about the parameters and calculation amount of your various size models. 
Can you tell me? 
Thank you

**Comment by AlexDotHam** [comment]
That can be my pleasure:
| Tracker | Parameter | Flops | FPS |
|----------|----------|----------|----------|
| ARTrack-B_256 | 172M | 57.6G | 26 |
| ARTrack-B_384 | 172M | 128G | 21 |
|ARTrack-L_384 | 458M | 346G | 16 |

**Comment by jiabingxiing** [comment]
Thank you!

**Comment by jiabingxiing** [comment]
By the way, can you tell me the number of parameters and calculations for ARTrack-v2, please?

**Comment by AlexDotHam** [comment]
Sure
| Tracker | Parameter | MACs| FPS |
|----------|----------|----------|----------|
| ARTrackV2-B_256 | 101M + 25M | 45G| 95 |
| ARTrackV2-B_384 | 101M + 25M| 98G | 74 |
| ARTrackV2-L_384 | 379M + 26M| 339G | 48 |

The plus before is the params of Encoder, and the 25M or 26M is about the masked decoder. When I wrote the paper, I forgot to calculate the decoder part of the params, I am so sorry for that when I checked today. The table.2 when I + appearance evolution, I actually add the extra encoder-layer, thus the params increase, I mistakenly believed that this was because I calculated the correct number of parameters increase from masked-decoder.

When I calculate flops, there seems like something wrong when I use fvcore, because some operation cannot be calculate, so I am not sure about the number of that.
